# Generated by Django 5.2.6 on 2025-09-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbaseduser',
            name='full_name',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
