# Generated by Django 5.2.6 on 2025-09-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailbaseduser_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailbaseduser',
            name='username',
        ),
    ]
