# Generated by Django 5.2.6 on 2025-09-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_emailbaseduser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='emailbaseduser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='emailbaseduser',
            name='full_name',
            field=models.CharField(max_length=1024),
        ),
    ]
