# Generated by Django 5.2.6 on 2025-09-14 07:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('query_preview', models.CharField(blank=True, max_length=512)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 9, 14, 7, 50, 20, 88709, tzinfo=datetime.timezone.utc))),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2025, 9, 14, 7, 50, 20, 88722, tzinfo=datetime.timezone.utc))),
                ('message_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
