# Generated by Django 5.2.6 on 2025-09-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_created_date_alter_chat_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
