# Generated by Django 5.2.6 on 2025-09-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_created_date_alter_chat_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message_count',
            field=models.IntegerField(default=1),
        ),
    ]
